In [4]:
!pip install pandas

^C

Collecting pandas
  Using cached pandas-2.0.3-cp38-cp38-win_amd64.whl (10.8 MB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\samee\onedrive\desktop\cicoproject\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Collecting tzdata>=2022.1
  Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Collecting numpy>=1.20.3; python_version < "3.10"
  Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
Requirement already satisfied: six>=1.5 in c:\users\samee\onedrive\desktop\cicoproject\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.24.4 pandas-2.0.3 pytz-2025.2 tzdata-2025.2

In [9]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.3.2-cp38-cp38-win_amd64.whl (9.3 MB)
Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\samee\onedrive\desktop\cicoproject\myenv\lib\site-packages (from scikit-learn) (1.24.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\samee\onedrive\desktop\cicoproject\myenv\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\samee\onedrive\desktop\cicoproject\myenv\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\samee\onedrive\desktop\cicoproject\myenv\lib\site-packages (from scikit-learn) (3.5.0)
Installing collected packages: scikit-learn
Successfully installed scikit-learn-1.3.2

WARNING: You are using pip version 20.1.1; however, version 25.0.1 is available.
You should consider upgrading via the 'c:\users\samee\onedrive\desktop\cicoproject\myenv\scripts\python.exe -m pip install --upgrade pip' command.

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import joblib

In [7]:
data={
    'Math':[78,45,90,35,65,82,30,40,55,92],
    'Science':[69,40,95,30,70,75,20,45,60,98],
    'English':[72,39,88,25,60,85,28,50,58,93],
    'Result':['Pass','Fail','Pass','Fail','Pass','Pass','Fail','Fail','Pass','Pass']
}
df=pd.DataFrame(data)
df

   Math  Science  English Result
0    78       69       72   Pass
1    45       40       39   Fail
2    90       95       88   Pass
3    35       30       25   Fail
4    65       70       60   Pass
5    82       75       85   Pass
6    30       20       28   Fail
7    40       45       50   Fail
8    55       60       58   Pass
9    92       98       93   Pass

In [8]:
df['Result']=df['Result'].map({'Pass':1,'Fail':0})
df

   Math  Science  English  Result
0    78       69       72       1
1    45       40       39       0
2    90       95       88       1
3    35       30       25       0
4    65       70       60       1
5    82       75       85       1
6    30       20       28       0
7    40       45       50       0
8    55       60       58       1
9    92       98       93       1

In [9]:
X=df[['Math','Science','English']]
Y=df['Result']
X

   Math  Science  English
0    78       69       72
1    45       40       39
2    90       95       88
3    35       30       25
4    65       70       60
5    82       75       85
6    30       20       28
7    40       45       50
8    55       60       58
9    92       98       93

In [10]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [11]:
x_train

   Math  Science  English
5    82       75       85
0    78       69       72
7    40       45       50
2    90       95       88
9    92       98       93
4    65       70       60
3    35       30       25
6    30       20       28

In [12]:
x_test

   Math  Science  English
8    55       60       58
1    45       40       39

In [13]:
y_train

5    1
0    1
7    0
2    1
9    1
4    1
3    0
6    0
Name: Result, dtype: int64

In [14]:
y_test

8    1
1    0
Name: Result, dtype: int64

In [15]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [16]:
joblib.dump(model,'model.pkl')

['model.pkl']

In [17]:
math = int(input('Enter the marks of Math: '))
science = int(input('Enter the marks of Science: '))
english = int(input('Enter the marks of English: '))

# Predict
result = model.predict([[math, science, english]])

if result[0] == 1:
    print('Pass')
else:
    print('Fail')

Fail

c:\Users\samee\OneDrive\Desktop\CICOPROJECT\myenv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(